[package]
authors = ["Jan Walter <jan@janwalter.com>"]
edition = "2018"
name = "rs_pbrt"
version = "0.9.3"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/wahn/rs_pbrt"
documentation = "https://www.rs-pbrt.org/doc/crates/rs_pbrt/index.html"
description = "Physically based rendering (PBR) with Rust"
homepage = "https://www.rs-pbrt.org"

[dependencies]
atom = "0.4.0"
atomic = "0.5.0"
byteorder = "1.4.3"
hexf = "0.2.1"
image = "0.23.14"
impl_ops = "0.1.1"
lazy_static = "1.4.0"
num = "0.4.0"
pest = "2.1.3"
pest_derive = "2.1.0"
ply-rs = "0.1.3"
smallvec = "1.6.1"
structopt = "0.3.21"
strum = "0.21.0"
strum_macros = "0.21.1"
typed-arena = "2.0.1"
wasm-bindgen = "0.2"
fastly = "^0.6.0"

[lib]
crate-type = ["cdylib"]
name = "rs_pbrt"

[[bin]]
name = "rs_pbrt_ecp"